on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
  INTROSPECTION_TOKEN: ${{ secrets.SPENTIFY_INTROSPECTION_TOKEN }}
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Bump version
        run: ./gradlew :app:bumpVersionCode
      - name: Commit back bumped version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip ci] Bump version code'
          file_pattern: 'app/build.gradle.kts'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json
      - name: Load keystore file
        env:
          DATA: ${{ secrets.NESSDEV_KEYSTORE }}
        run: echo $DATA | base64 -di > app/sign.keystore
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update Production GraphQL schema
        run: ./gradlew :app:lib:schema:downloadSpentifyApolloSchema
      - name: Generate signed APK
        run: ./gradlew :app:assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
          overwrite: true
