name: PR Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update Production GraphQL schema
        run: ./gradlew :app:lib:schema:downloadApolloSchema --endpoint='https://spentify.nestorperez.dev/graphql/' --schema=app/lib/schema/src/main/graphql/schema.sdl
      - name: Build
        run: ./gradlew :app:assemble
