name: PR Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
env:
  INTROSPECTION_TOKEN: ${{ secrets.SPENTIFY_INTROSPECTION_TOKEN }}
jobs:
  screenshot-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate screenshots
        run: ./gradlew validateDebugScreenshotTest
      - name: Upload results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-results
          path:
            - app/uikit/build/reports/screenshotTest/preview/debug
            - app/account/build/reports/screenshotTest/preview/debug
            - app/auth/build/reports/screenshotTest/preview/debug